CREATE USER jpa_client WITH PASSWORD 'secret';

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jpa_client;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id BIGINT,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    valid_until TIMESTAMP(6) WITH TIME ZONE,
    question VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE vote_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    poll_id BIGINT,
    presentation_order BIGINT NOT NULL,
    caption VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (poll_id) REFERENCES poll (id)
);

CREATE TABLE vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    published_at TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT,
    vote_option_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (vote_option_id) REFERENCES vote_option (id)
);
