services:

  mongodb-analytics:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mongodb-analytics'
      - 'MONGO_INITDB_ROOT_PASSWORD=TopSecret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
    container_name: mongodb-analytics
    volumes:
      - mongodb_analytics_data:/data/db

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    container_name: pollapp-postgres
    volumes:
      - ./backend/database/postgres/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
      - ./backend/database/postgres/mock-data.sql:/docker-entrypoint-initdb.d/mock-data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      timeout: 5s

  rabbitmq:
    image: 'rabbitmq:3-management'  
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'    
      - '15672:15672' 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.uri" : "mongodb://root:TopSecret@mongodb-analytics:27017/mongodb-analytics?authSource=admin",
        "spring.rabbitmq.host": "rabbitmq",
        "spring.rabbitmq.port": "5672",
        "spring.rabbitmq.username": "myuser",
        "spring.rabbitmq.password": "secret"
      }'

    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]
    depends_on:
      postgres:
        condition: service_healthy



volumes:
  mongodb_analytics_data:
  rabbitmq_data:

