alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
alter table if exists poll drop constraint if exists FKt0fx2lmnciaxhg5gmbb41veel;
alter table if exists vote drop constraint if exists FKkmvvqilx49120p47nr9t56omf;
alter table if exists vote drop constraint if exists FKh8ws1u4yubjccgtjtpmb2f4rb;
alter table if exists vote_option drop constraint if exists FKc3kqmx2cig1mb3kid3gjwtx2a;
drop table if exists poll cascade;
drop table if exists users cascade;
drop table if exists vote cascade;
drop table if exists vote_option cascade;
