CREATE USER jpa_client WITH PASSWORD 'secret';

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jpa_client;

create table Users (
    id bigint generated by default as identity,
    username varchar(255),
    password varchar(255),
    email varchar(255),
    primary key (id)
);
insert into Users (username, password, email) VALUES ('eivind', 'hallo123', 'hei@teit.com');
