name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build and Link frontend to backend
        run: ./gradlew copyWebApp

      - name: Build Gradle Backend
        run: ./gradlew build
        working-directory: ./backend

      - name: Run Backend Tests
        run: .gradlew test
        working-directory: ./backend



